config/routes.rb
Rails.application.routes.draw do
  root to: "questions#index"

  resources :questions do
    resources :answers
  end

  resources :answers do
    resources :votes
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates :body, presence: :true
  has_many :votes
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  accepts_nested_attributes_for :answers, allow_destroy: true
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :answer
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @answers = Answer.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
    @answers = Answer.all
  end

  def new
    @question = Question.new
    2.times { @question.answers.build}
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      respond_to do |format|
        format.html { redirect_to questions_path }
        format.js
      end
    else
      render :new
    end
  end

  private
    def question_params
      params.require(:question).permit(answers_attributes: [:id, :body])
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @answer = Answer.find(params[:answer_id])
    @vote = @answer.votes.create
    respond_to do |format|
      format.html { redirect_to questions_path}
      format.js
    end
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Good Choices</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<div class='container'>
<body>
<nav>
  <h1>Choices, Choices</h1>
  <%= yield(:nav) %>
</nav>
<%= yield %>

</body>
</div>
</html>

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  Options:
  <ul>
    <%= f.fields_for :answers do |answers_form| %>
      <li>
        <%= answers_form.label :option %>
        <%= answers_form.text_field :body %>
      </li>
    <% end %>
    <br>
    <%= f.submit "Submit" %>
  </ul>
<% end %>

app/views/questions/create.js.erb
$('form').remove();
('#new_question_link').show();

app/views/questions/index.html.erb
<% content_for(:nav) do %>
<% end %>
<hr>

<ul>
  <% @questions.each do |question| %>
    <div id="question_<%=question.id%>">
      <h2>Would you rather ?</h2>

      <%= link_to question.answers.first.body, answer_votes_path(question.answers.first), method: "post", remote: true  %>
      <span id="answer_<%=question.answers.first.id%>"><%= question.answers.first.votes.count %></span>

      <%= link_to question.answers.last.body,answer_votes_path(question.answers.last), method: "post",  remote: true %>
      <span id="answer_<%=question.answers.last.id%>"><%= question.answers.last.votes.count %></span>

    </div>
    <hr>
  <% end %>
</ul>

<br>
<br>
<div class="container-fluid">
<%= link_to "Add a Question", new_question_path, id: "new_question_link", class: "btn btn-info", remote: true %>
</div>

app/views/questions/new.html.erb
<h1>Create a new question</h1>

<%= render 'form' %>

app/views/questions/new.js.erb
$('#new_question_link').hide().after('<%= j render("form") %>')

app/views/votes/create.js.erb
$('#answer_<%= @answer.id %>').text(<%= @answer.votes.count %>);